language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

before_install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email:
    - info@endroid.nl
